In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
'date': ['2024-03-01', '2024-03-01', '2024-03-02', '2024-03-02'],
 'product': ['Latte', 'Americano', 'Latte', 'Cappuccino'],
'price': [38.7, 28.9, 38.7, 32.0],
  'quantity': [2, 1, 3, 2]
  }
df = pd.DataFrame(data)
df

         date     product  price  quantity
0  2024-03-01       Latte   38.7         2
1  2024-03-01   Americano   28.9         1
2  2024-03-02       Latte   38.7         3
3  2024-03-02  Cappuccino   32.0         2

In [3]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/messi barca.csv', encoding='latin1')
df.head()

Mounted at /content/drive

,Season,Age,Competition,Matches Played,Starts,Minutes played,Goals scored,Assists,PK,PKatt,CrdY,CrdR,Goal/90,Ast/90,G+A/90,G-PK/90,G+A-PK/90
0,2004-2005,17,Champions League,1,1,90,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00
1,2004-2005,17,La Liga,7,0,70,1,0,0,0,0,0,1.29,0.00,1.29,1.29,1.29
2,2005-2006,18,Champions League,6,4,322,1,1,0,0,0,0,0.28,0.28,0.56,0.28,0.56
3,2005-2006,18,La Liga,17,11,911,6,3,0,0,2,0,0.59,0.30,0.89,0.59,0.89
4,2006-2007,19,Champions League,5,4,385,1,0,0,0,1,0,0.23,0.00,0.23,0.23,0.23

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Season          44 non-null     object
 1   Age             44 non-null     int64
 2   Competition     44 non-null     object
 3   Matches Played  44 non-null     int64
 4   Starts          44 non-null     int64
 5   Minutes played  44 non-null     int64
 6   Goals scored    44 non-null     int64
 7   Assists         44 non-null     int64
 8   PK              44 non-null     int64
 9   PKatt           44 non-null     int64
 10  CrdY            44 non-null     int64
 11  CrdR            44 non-null     int64
 12  Goal/90         44 non-null     float64
 13  Ast/90          44 non-null     float64
 14  G+A/90          44 non-null     float64
 15  G-PK/90         44 non-null     float64
 16  G+A-PK/90       44 non-null     float64
dtypes: float64(5), int64(10), object(2)
memory usage: 6.0+ KB

,Age,Matches Played,Starts,Minutes played,Goals scored,Assists,PK,PKatt,CrdY,CrdR,Goal/90,Ast/90,G+A/90,G-PK/90,G+A-PK/90
count,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.0,44.000000,44.000000,44.000000,44.000000,44.000000
mean,25.886364,15.159091,13.636364,1237.068182,13.386364,5.431818,1.659091,2.022727,1.500000,0.0,0.847727,0.351591,1.199318,0.756591,1.107727
std,4.666635,12.860510,11.941896,1084.253326,14.203203,5.903872,2.322220,2.663174,1.562645,0.0,0.361713,0.261924,0.424485,0.344235,0.414268
min,17.000000,1.000000,0.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,22.000000,5.750000,4.000000,387.250000,2.750000,1.000000,0.000000,0.000000,0.000000,0.0,0.677500,0.200000,0.997500,0.612500,0.867500
50%,27.000000,10.000000,9.000000,818.000000,8.000000,3.000000,1.000000,1.000000,1.000000,0.0,0.860000,0.365000,1.290000,0.760000,1.185000
75%,30.000000,31.000000,27.250000,2504.750000,23.500000,9.500000,3.000000,4.000000,2.000000,0.0,1.102500,0.482500,1.470000,0.992500,1.375000
max,32.000000,38.000000,37.000000,3375.000000,50.000000,20.000000,10.000000,11.000000,6.000000,0.0,1.560000,1.000000,1.940000,1.500000,1.870000

All columns are divided into three data types:
  Text / Categorical columns (object - 2 columns)   :

    Season   
    Competition
  Integer numeric columns (int64 - 10 columns)
    
    Age   
    Matches
    Played   
    Starts   
    Minutes played  
    Goals scored  
    Assists   
    PK   
    PKatt   
    CrdY   
    CrdR

  Floating-point columns (float64 - 5 columns)
  
    Goal/90   
    Ast/90   
    G+A/90   
    G-PK/90   
    G+A-PK/90

In [5]:
row_iloc = df.iloc[2]
print(row_iloc)

Season                   2005-2006
Age                             18
Competition       Champions League
Matches Played                   6
Starts                           4
Minutes played                 322
Goals scored                     1
Assists                          1
PK                               0
PKatt                            0
CrdY                             0
CrdR                             0
Goal/90                       0.28
Ast/90                        0.28
G+A/90                        0.56
G-PK/90                       0.28
G+A-PK/90                     0.56
Name: 2, dtype: object

In [6]:
row_loc = df.iloc[2]
print(row_loc)

Season                   2005-2006
Age                             18
Competition       Champions League
Matches Played                   6
Starts                           4
Minutes played                 322
Goals scored                     1
Assists                          1
PK                               0
PKatt                            0
CrdY                             0
CrdR                             0
Goal/90                       0.28
Ast/90                        0.28
G+A/90                        0.56
G-PK/90                       0.28
G+A-PK/90                     0.56
Name: 2, dtype: object

In [7]:
value = df.loc[5, 'Goals scored']
print(value)

14

In [9]:
mask_high = df['Goals scored'] > 20
high_goals = df[mask_high]
print(high_goals.head())

       Season  Age Competition  Matches Played  Starts  Minutes played  \
9   2008-2009   21     La Liga              31      27            2516
11  2009-2010   22     La Liga              35      30            2805
13  2010-2011   23     La Liga              33      31            2858
15  2011-2012   24     La Liga              37      36            3270
17  2012-2013   25     La Liga              32      28            2650

    Goals scored  Assists  PK  PKatt  CrdY  CrdR  Goal/90  Ast/90  G+A/90  \
9             23       11   3      4     2     0     0.82    0.39    1.22
11            34        9   1      1     3     0     1.09    0.29    1.38
13            31       19   4      4     3     0     0.98    0.60    1.57
15            50       16  10     11     6     0     1.38    0.44    1.82
17            46       11   4      4     1     0     1.56    0.37    1.94

    G-PK/90  G+A-PK/90
9      0.72       1.11
11     1.06       1.35
13     0.85       1.45
15     1.10       1.54
17     1.43       1.80

In [10]:
sorted_goals = df.sort_values('Goals scored', ascending=False)
print(sorted_goals.head())

       Season  Age Competition  Matches Played  Starts  Minutes played  \
15  2011-2012   24     La Liga              37      36            3270
17  2012-2013   25     La Liga              32      28            2650
22  2014-2015   27     La Liga              38      37            3375
30  2016-2017   29     La Liga              34      32            2828
38  2018-2019   31     La Liga              34      29            2713

    Goals scored  Assists  PK  PKatt  CrdY  CrdR  Goal/90  Ast/90  G+A/90  \
15            50       16  10     11     6     0     1.38    0.44    1.82
17            46       11   4      4     1     0     1.56    0.37    1.94
22            43       18   5      6     4     0     1.15    0.48    1.63
30            37        9   6      7     6     0     1.18    0.29    1.46
38            36       13   4      5     3     0     1.19    0.43    1.63

    G-PK/90  G+A-PK/90
15     1.10       1.54
17     1.43       1.80
22     1.01       1.49
30     0.99       1.27
38     1.06       1.49

In [11]:
final = df[df['Goals scored'] > 35].sort_values('Goals scored', ascending=False)
final.to_csv('/content/drive/MyDrive/filtered_messi.csv', index=False)
print("Файл збережено!")

Файл збережено!

In [14]:
df = pd.read_csv('/content/drive/MyDrive/messi barca.csv', encoding='utf-8', encoding_errors='ignore')

print("=== Task 2: Перші 3 рядки датасету ===")
print(df.head(3))

print("\n=== Task 2: Останні 3 рядки датасету ===")
print(df.tail(3))
print("\n" + "="*50 + "\n")

=== Task 2: Перші 3 рядки датасету ===
      Season  Age       Competition  Matches Played  Starts  Minutes played  \
0  2004-2005   17  Champions League               1       1              90
1  2004-2005   17           La Liga               7       0              70
2  2005-2006   18  Champions League               6       4             322

   Goals scored  Assists  PK  PKatt  CrdY  CrdR  Goal/90  Ast/90  G+A/90  \
0             0        0   0      0     0     0     0.00    0.00    0.00
1             1        0   0      0     0     0     1.29    0.00    1.29
2             1        1   0      0     0     0     0.28    0.28    0.56

   G-PK/90  G+A-PK/90
0     0.00       0.00
1     1.29       1.29
2     0.28       0.56

=== Task 2: Останні 3 рядки датасету ===
       Season  Age         Competition  Matches Played  Starts  \
41  2019-2020   32        Copa del Rey               2       2
42  2019-2020   32             La Liga              33      32
43  2019-2020   32  Supercopa de Espaa               1       1

    Minutes played  Goals scored  Assists  PK  PKatt  CrdY  CrdR  Goal/90  \
41             180             2        1   0      0     1     0     1.00
42            2880            25       20   5      5     4     0     0.78
43              90             1        0   0      0     0     0     1.00

    Ast/90  G+A/90  G-PK/90  G+A-PK/90
41    0.50    1.50     1.00       1.50
42    0.62    1.41     0.62       1.25
43    0.00    1.00     1.00       1.00

==================================================

In [15]:
import pandas as pd

def group_and_sort_by_column(df, column_name):
    result_df = df[column_name].value_counts().reset_index()

    result_df.columns = [column_name, 'count']

    result_df = result_df.sort_values(by='count', ascending=False)

    return result_df

competition_stats = group_and_sort_by_column(df, 'Competition')

print("=== Результат групування та сортування Competition ===")
print(competition_stats)

competition_stats.to_csv('/content/drive/MyDrive/competition_summary.csv', index=False)
print("\nРезультат успішно збережено у файл 'competition_summary.csv'")

=== Результат групування та сортування Competition ===
          Competition  count
0    Champions League     16
1             La Liga     16
2        Copa del Rey      6
3  Supercopa de Espaa      5
4           Super Cup      1

Результат успішно збережено у файл 'competition_summary.csv'